// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OsDbWebApi.Models;

#nullable disable

namespace OsDbWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230225185105_new_migration2")]
    partial class new_migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OsDbWebApi.Models.Entity.OperationSystems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EntityOperationSystems");
                });

            modelBuilder.Entity("OsDbWebApi.Models.Entity.OsVersions", b =>
                {
                    b.Property<int>("VersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VersionID"));

                    b.Property<string>("Futures")
                        .HasColumnType("text");

                    b.Property<int?>("PhoneOperationSystemsPhoneOsID")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneOsID")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("text");

                    b.Property<string>("VersionName")
                        .HasColumnType("text");

                    b.HasKey("VersionID");

                    b.HasIndex("PhoneOperationSystemsPhoneOsID");

                    b.ToTable("EntityOsVersions");
                });

            modelBuilder.Entity("OsDbWebApi.Models.Entity.PhoneOperationSystems", b =>
                {
                    b.Property<int>("PhoneOsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhoneOsID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .HasColumnType("text");

                    b.HasKey("PhoneOsID");

                    b.ToTable("EntityPhoneOs");
                });

            modelBuilder.Entity("OsDbWebApi.Models.Entity.OsVersions", b =>
                {
                    b.HasOne("OsDbWebApi.Models.Entity.PhoneOperationSystems", null)
                        .WithMany("Versions")
                        .HasForeignKey("PhoneOperationSystemsPhoneOsID");
                });

            modelBuilder.Entity("OsDbWebApi.Models.Entity.PhoneOperationSystems", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
